(function(root, factory){
  const api = factory();
  if(typeof module === 'object' && module.exports) module.exports = api;
  root.ShohizeiRelease = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function(){
  'use strict';

  const RELEASE_HISTORY = Object.freeze([
    Object.freeze({
      version:'r32.1',
      date:'2026-09-25',
      title:'STEP4の前期仮定保存・0回判定・国税代理額を修正',
      category:'correction',
      recalcRecommended:true,
      changes:Object.freeze([
        '両案の別前期仮定をチェック状態で保存・復元し、旧r32の判別不能な保存値は再確認まで未算定にする',
        '自動判定0回と手入力の空欄を分け、片案0回・両案0回と自動から手入力への切替を正しく精算する',
        '国税内訳不明の本則個別調整があるSTEP3代理額の自動予定を止め、前期確定国税額の入力へ案内する'
      ])
    }),
    Object.freeze({
      version:'r32',
      date:'2026-09-25',
      title:'食品対象額の一括転記と中間納付の前期実績方式による自動設定',
      category:'usability',
      recalcRecommended:false,
      changes:Object.freeze([
        'STEP2の軽減8％売上・仕入行から食品対象額へ一度だけ転記し、既存値の上書きは一括確認',
        'STEP4で前期国税額を基礎とする0・1・3・11回の中間納付予定を日付・国税・地方税別に生成',
        'STEP3前期代理の概算と実際の前期入力を区別し、休日繰延べ・法人延長・未確認を表示と出力に反映'
      ])
    }),
    Object.freeze({
      version:'r31.1',
      date:'2026-09-25',
      title:'STEP4の返品・月別配分と確認状態を修正',
      category:'correction',
      recalcRecommended:true,
      changes:Object.freeze([
        '売上返還等の食品内数を減算し、年間差引0円でも復元できる月別の資金増減を維持',
        'リセットと別CSV反映で納付予定・元資料確認状態を適切に初期化し、対象外月への端数配分を防止',
        '支払・納付の資金寄与と売上／仕入別の月別配分方法を画面・コピー・CSV・印刷で明示'
      ])
    }),
    Object.freeze({
      version:'r31',
      date:'2026-09-25',
      title:'食品1％試算に資金繰りへの影響（STEP4）を追加',
      category:'usability',
      recalcRecommended:false,
      changes:Object.freeze([
        '表示上のSTEP4を追加し、既存STEP3と同じ方式・入力・税額を使って月別の税込入出金差と税金精算差を試算',
        '中間納付・確定納付・還付を両案別に置き、当期税額の二重計上を防止。未確認時は税金未反映の部分試算として区別',
        'CSV補正・仮除外後の匿名化月別構成、手入力、保存復元、専用コピー・CSV・印刷に対応。元資料期間を確認できない場合は均等配分と明示'
      ])
    }),
    Object.freeze({
      version:'r30',
      date:'2026-09-24',
      title:'現行制度の申告書段階計算を全結果・出力へ統一',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        '手入力・CSVとも現在の課税区分別行から、売上返還等を分けて本則の付表2-3→付表1-3→第一表を再計算',
        '簡易課税・2割・3割特例も現行制度の端数処理後の税額を比較・4期累計・コピー・CSV・印刷に使用',
        '無変更のフォーカス移動ではCSV由来を維持。行変更で再計算し、必要情報不足は概算に戻さず未算定理由を表示',
        'CSVの仮定・明示仮除外では厳密再現未完了を保ち、計算可能な行の申告書段階で丸めた税額を参考表示・出力。貸借の表記を統一',
        '食品1％試算の期間別金額は日数均等按分を先頭・初期選択の原則として表示し、手入力方式と保存済み選択は維持'
      ])
    }),
    Object.freeze({
      version:'r29.2',
      date:'2026-09-24',
      title:'比較方式に応じた必要列・キー移動と結果表示を整理',
      category:'usability',
      recalcRecommended:false,
      changes:Object.freeze([
        '選択した方式・税率シナリオに必要な売上・仕入列だけを表示し、Enter・Tab移動も同じ条件へ統一。非表示の入力値は保持',
        '方式選択に全選択と選択済み印を追加し、初期案内と未選択で進もうとした際の警告を区別',
        '行入力表の幅、固定サマリー、単独試算と複数方式の結果表示を整理。税額算式・適用判定は不変更'
      ])
    }),
    Object.freeze({
      version:'r29.1',
      date:'2026-09-23',
      title:'本則の現行入力判定・明示1％CSV割合・過年度換算前提を修正',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        'R01：非表示の旧控除設定に依存せず、現在の仕入金額・計算条件と届出による選択可否を別に判定。未入力と明示0円を区別',
        'R02：CSV明示1％の免税事業者等仕入も元取引日と控除割合を照合。不整合の本則・4期累計は未算定にし、元値と理由を保持',
        'R02追補：保存済み明示1％仕入の70％・0.7を統一し、金額・割合の不正は本則3計算法へ共通反映。明細と表示集計の不整合を解消',
        'R03：過年度CSVの元割合から対象期への日数加重換算を、通常コピー・CSV・印刷の共通前提へ表示。税額算式は不変更'
      ])
    }),
    Object.freeze({
      version:'r29',
      date:'2026-09-23',
      title:'行入力の用途別再計算とCSV反映・控除割合の整合修正',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        'F01：食品1％試算で仕入総額と課税売上対応・非課税売上対応・共通対応の税額を同じ元行から再計算。旧形式で復元不能な用途別額は未算定',
        'F02：CSV反映は置換を標準とし、手入力行を残す追加は明示選択。再反映時は旧CSV行・実績・確認情報を更新',
        'F03：4期見通しの将来控除割合を元の仕入金額・税率・用途へ適用し、総額と用途別額を同時に再集計',
        'F04：控除割合と取引日・課税期間の矛盾を本則・4期累計の未算定と出力の確認事項へ反映。過年度CSV実績と予測対象期を区別'
      ])
    }),
    Object.freeze({
      version:'r28',
      date:'2026-09-23',
      title:'方式別比較の強調と判定・CSV由来の整合修正',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        '金額・差額を大きく右揃えし、計算方法と確認事項を各方式の下へ分離',
        '通常印刷を方式別比較と前提条件に絞り、食品1％の現行税率・差額も同じ金額で印刷',
        '通常印刷はA4縦1ページを原則とし、縮小後の再測定と7ptの可読性を優先して必要なら複数ページを許容。重複注記を整理',
        '印刷専用帳票の確認理由を方式・税率間で集約し、セル余白・行間を圧縮。背景グラフィック有効時のページ背景を白に指定',
        '当期と4期で簡易課税継続・不適用届出の選択可否を共通化。期間エラーは全方式を未算定に変更',
        '詳細試算の表示切替で方式選択可否を変えず、選択可否未確認の本則税額は最有利候補から除外。適用対象外方式の一般的な参考値表示を抑止',
        '免税仕入の未確認とCSV元期間を参考比較に残し、返品相殺で既知の売上0円を未入力と区別'
      ])
    }),
    Object.freeze({
      version:'r27',
      date:'2026-09-23',
      title:'CSV入口・文字サイズの整理と結果比較表の統合',
      category:'display',
      recalcRecommended:false,
      changes:Object.freeze([
        'CSV入口では取込欄だけを開き、ファイル選択は利用者の操作で開始',
        '表内を含む入力値とラベルを14px、補足文を12pxの基準に統一',
        '方式別結果を一覧表にし、1％モードでは同じ表に現行税率・差額列を表示。計算過程・未確認事項を保持'
      ])
    }),
    Object.freeze({
      version:'r26',
      date:'2026-09-23',
      title:'飲食料品1％試算に現行税率との差額表を追加',
      category:'display',
      recalcRecommended:false,
      changes:Object.freeze([
        '税額の比較画面に、方式別の現行税率・飲食料品1％試算・増減額を並べる表を追加',
        '同じ入力から既存の計算処理で現行税率を再計算。未確認・仮定・対象外を保持',
        '明示1％CSVは比較元資料が必要と表示。既存税額・計算過程・顧客用出力は維持'
      ])
    }),
    Object.freeze({
      version:'r25',
      date:'2026-09-23',
      title:'不完全なCSVも仮定を置いて概算へ進む',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        '主ボタンで仮定・対象額を一度確認し、税率・控除割合・事業区分が不明でも参考試算へ進む',
        '金額・分類不明は仮除外、1％以外の負集計は明示0円仮置き。用途別と全体を再集計',
        '仮定を結果・計算過程・出力・保存に保持し、確認済みや有利方式の確定にしない。税額公式・端数処理は維持'
      ])
    }),
    Object.freeze({
      version:'r24',
      date:'2026-09-18',
      title:'CSV問題明細の補正・明示除外と参考試算',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        '問題のある貸借明細だけを補正・仮除外・対象外確認し、元CSVから再集計して明示反映',
        '除外の件数・絶対額・不明額件数と参考状態を結果、計算過程、出力、保存復元へ連携',
        '正常CSVの手順、税額公式、端数表示、3段階の導線を維持。構造不良は部分反映不可'
      ])
    }),
    Object.freeze({
      version:'r23',
      date:'2026-09-18',
      title:'本則課税の計算条件を基本画面へ移動',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        '計算過程の金額を円単位表示へ整理。税額計算・判定は変更なし',
        '最終調整：入力直後のクリックを妨げるナビゲーションの不要なDOM移動を抑止し、詳細試算の説明を更新',
        '現在の申告方式の直下に本則の比較設定、金額画面に非課税売上等と必要な用途別税額を配置',
        '本則の計算方法を詳細試算から独立させ、未入力は本則だけ未算定として案内',
        '旧概算率は適用せず入力値を保持して再確認。既存の公式・丸め・他方式を維持'
      ])
    }),
    Object.freeze({
      version:'r22',
      date:'2026-09-17',
      title:'入力から税額比較までを3段階に整理',
      category:'display',
      recalcRecommended:false,
      changes:Object.freeze([
        '手入力とCSVを同じ強さの入口で並べ、事業者・対象期間、金額入力、税額比較の3段階へ統一',
        '食品額の確認と基準期間・特定期間の既存入力を金額画面に移し、結果から該当欄へ戻る案内を追加',
        '追加費用は税額結果の後半で任意に開き、参考税額と適用条件の確認状況を分かりやすく表示'
      ])
    }),
    Object.freeze({
      version:'r21',
      date:'2026-09-17',
      title:'結果カードから実入力の計算過程を確認',
      category:'display',
      recalcRecommended:false,
      changes:Object.freeze([
        '各方式の結果カードに、実際の入力額・税率・控除・採用方式・端数処理を追える任意の計算過程を追加',
        '食品1％の予測とCSV明示実績、簡易75％候補、追加費用差額、現行4期累計の内訳を表示',
        '税額計算・適用判定・通常入力を変更せず、計算過程は顧客用コピー・CSV・印刷に自動追加しない'
      ])
    }),
    Object.freeze({
      version:'r20',
      date:'2026-09-17',
      title:'手入力を主入口にし、確認事項と参考試算を分離',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        'CSVなしで金額入力へ直接進める入口と、任意で開くCSV取込みを追加',
        '明示1％の返品・種別不明は元取引未確認を残し、算定できる場合だけ入力税率を仮定した参考値として表示',
        '届出・元取引の確認手順を担当者向け詳細欄へ示し、顧客用には未確定事項を中立的に表示'
      ])
    }),
    Object.freeze({
      version:'r19',
      date:'2026-09-17',
      title:'届出判定の開始日とCSV調整仕訳の確認を整合',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        '届出特例が対象外・要確認のときは適用開始見込み日と2年継続要件解除の断定を消し、対象外理由を顧客用出力へ反映',
        '期首前届出は通常の届出要件と法案成立後の特例による事前提出をともに確認する案内へ変更',
        'CSVの1％返品・調整と取引種別不明は計上日が対象期間内でも元取引の税率確認が必要として比較を停止'
      ])
    }),
    Object.freeze({
      version:'r18',
      date:'2026-09-17',
      title:'1％実績の期間検証と切替判断の最終調整',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        'CSV明示1％取引を取引日と制度期間で照合し、期間外の通常取引を停止、返還・調整を要個別確認へ分離',
        '期首前の不適用届出を特例による切替不可と断定せず、通常の届出経路と2年継続適用要件を確認',
        '現行税率の4期試算に未施行期間が重なるとき、全期10％・8％で食品1％提案は未反映と画面・出力に明記',
        '追加支出後に残る差額を控除前提付きの単一主指標とし、控除未確認時の参考額を顧客出力へ統一'
      ])
    }),
    Object.freeze({
      version:'r17',
      date:'2026-09-17',
      title:'CSVの1％実績と予測を分離し、比較導線を整理',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        'CSVの明示1％実績を8％実績からの予測と分離し、元税率・税込額で売上と仕入を計算',
        '免税事業者等仕入の純額0円と取引なしを件数で区別し、0円入力による誤った矛盾判定を修正',
        '食品特例を含む4期最適経路を停止し、単期比較と措置終了後の確認を案内',
        '税率前提を検討目的と分離し、追加費用比較を任意操作へ変更',
        '追加控除未確認でも控除前の参考差額を表示し、提出予定と提出済みの顧客表示を区別'
      ])
    }),
    Object.freeze({
      version:'r16',
      date:'2026-09-16',
      title:'入力導線と追加負担の比較を明確化',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        '会社・期間・データ、売上・仕入、追加負担、結果・確認事項の4画面へ整理し、税理士確認項目を結果画面に集約',
        '食品1％対象売上を各事業区分の軽減8％欄に併記し、事業区分・免税事業者等仕入の表示を必要な範囲へ絞る',
        '追加報酬の税抜・税込見積と確認済み仕入控除を分け、税込支出から未反映の控除を一度だけ反映',
        '不正な入力を0円に読み替えず、費用未入力と時間の金額換算なしを区別',
        '旧版の金額基準不明な追加報酬は再入力を求め、顧客用出力を確認済みと所内検討用に区別'
      ])
    }),
    Object.freeze({
      version:'r15',
      date:'2026-09-16',
      title:'飲食料品1％提案と一般課税切替判断に対応',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        '改正案・法案成立前の政策試算として、2027年4月1日から2029年3月31日までの飲食料品1％を期間判定',
        '食品1％売上税額の全額控除と、残余部分に対する簡易課税75％特例・2割・3割特例を反映',
        '新聞・旧税率適用食品・外食等を1％対象へ自動推定せず、未確認区分を保持',
        '簡易課税継続案と一般課税切替案を、税額差・追加支出・時間価値・所内採算に分けて比較',
        '顧客用コピー・CSV・印刷から所内工数原価・採算・内部メモを除外',
        'r14保存値を維持し、旧1％試算は食品等区分を未確認として移行'
      ])
    }),
    Object.freeze({
      version:'r14',
      date:'2026-09-16',
      title:'TKC仕訳帳CSVからの入力に対応',
      category:'calculation',
      recalcRecommended:false,
      changes:Object.freeze([
        'TKC仕訳帳CSVを端末内だけで解析し、課税売上・課税仕入等を入力欄へ反映',
        '借方・貸方、標準10％・軽減8％、免税事業者等仕入の控除割合を区分して集計',
        '簡易課税の事業区分が未設定の売上は勘定科目ごとの確認後に反映',
        '非課税売上と課税売上対応・共通対応の仕入税額を詳細試算へ連携',
        'UTF-8 BOM、UTF-8、Shift_JISのCSVに対応'
      ])
    }),
    Object.freeze({
      version:'r13',
      date:'2026-07-11',
      title:'4期最適化の届出経路と判定前提を改善',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        '2割・3割適用中に将来の簡易課税選択届出を行う経路を4期最適化へ追加',
        '当期の簡易課税不適用届出と将来届出の期限確認を分離',
        '1年未満の課税期間における5億円判定用課税売上高の年換算を追加',
        '調整対象固定資産100万円以上の別途制限と期首棚卸資産調整の注意を追加',
        '消費税率の前提を標準10％・軽減8％と明示'
      ])
    }),
    Object.freeze({
      version:'r12',
      date:'2026-07-11',
      title:'詳細試算と4期累計最適化を追加',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        '簡易課税の届出経路と原則2年継続を反映した4期累計最適化を追加',
        '課税売上割合、全額控除要件、個別対応方式、一括比例配分方式の詳細試算を追加',
        '高額特定資産等の金額・資産区分による段階式判定補助を追加',
        '税率別課税標準、国税・地方税の申告書段階の端数処理を追加',
        '通常画面の入力数を増やさず、必要な案件だけ詳細項目を表示'
      ])
    }),
    Object.freeze({
      version:'r11',
      date:'2026-07-11',
      title:'判定の安全性と計算精度を改善',
      category:'calculation',
      recalcRecommended:true,
      changes:Object.freeze([
        '0円を有効な入力として扱うよう修正',
        '売上ゼロ・仕入ありの本則課税による還付試算に対応',
        '簡易課税の1事業・2事業の75％特例に対応',
        '適用要件を確認済み候補・要確認・適用不可に区分',
        '4期比較を各期単独比較と明確化',
        '将来期の免税事業者仕入控除割合を日数按分へ変更',
        '入力値の端末保存を任意選択へ変更',
        'コピー・CSV・印刷へ前提条件と未確認事項を追加'
      ])
    })
  ]);

  const DEFERRED_LIMITATIONS = Object.freeze([
    '4期試算は現在の売上・仕入構成が続く仮定です。実際の届出提出日、過去の適用履歴、将来の取引予測は原資料で確認してください。',
    '課税売上割合に準ずる割合、非課税資産の輸出、特定課税仕入れ等がある場合は個別確認が必要です。',
    '自己建設高額特定資産、棚卸資産調整、居住用賃貸建物、相続・合併等は判定補助にとどまり、自動確定しません。',
    '現行制度の行入力による申告書段階計算は課税区分11の売上返還を扱います。仕入返還、貸倒れ、中間納付、旧税率、請求書単位の積上げ計算等は別途確認してください。'
  ]);

  const APP_META = Object.freeze({
    name:'消費税課税方式検討ツール（所内での一次試算用）',
    audience:'税理士等の専門家向け一次試算',
    version:RELEASE_HISTORY[0].version,
    updatedAt:RELEASE_HISTORY[0].date,
    currentLawBasisDate:'2026-07-11',
    currentLawBasisLabel:'2026年7月11日時点（国税庁公表資料ベース）',
    proposalBasisDate:'2026-09-15',
    proposalBasisLabel:'2026年9月15日受領・国税庁パンフレット「飲食料品に係る２年間の消費税率引下げについて」（令和8年9月）に基づく未施行試算',
    lawBasisDate:'2026-07-11',
    lawBasisLabel:'2026年7月11日時点（国税庁公表資料ベース）',
    latestReleaseTitle:RELEASE_HISTORY[0].title
  });

  return Object.freeze({ RELEASE_HISTORY, DEFERRED_LIMITATIONS, APP_META });
});
